/*
 * Test data strategy for ScaleIndex.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2017-10-09 22:23 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for ScaleIndex. Provides
 * test values for parameter "int size" 
 * of method "ScaleIndex(int, int, int)". 
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2017-10-09 22:23 +0200
 */
public /*@ nullable_by_default */ class ScaleIndex_ScaleIndex__int_intPart__int_fracPart__int_size__0__size
  extends ScaleIndex_ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int size".
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add local-scope int values or generators here */ });
  }
}
