/*
 * Test data strategy for SensorValue.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2017-10-09 22:23 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for SensorValue. Provides
 * test values for parameter "int failSafe" 
 * of method "SensorValue(int, int, int)". 
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2017-10-09 22:23 +0200
 */
public /*@ nullable_by_default */ class SensorValue_SensorValue__int_failSafe__int_minValue__int_maxValue__0__failSafe
  extends SensorValue_ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int failSafe".
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add local-scope int values or generators here */ });
  }
}
